; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.43"

; Modules
projects[ctools][version] = "1.9"

projects[date][version] = "2.9"

projects[entity][version] = "1.6"

projects[entityreference][version] = "1.1"

projects[profile2][version] = "1.3"

projects[shib_auth][version] = "4.3"

projects[url][version] = "1.0"

projects[views][version] = "3.13"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[shib_preprovision-7.x-1.0-beta1][download][type] = ""
projects[shib_preprovision-7.x-1.0-beta1][download][url] = ""
projects[shib_preprovision-7.x-1.0-beta1][type] = "module"

